Repository liteflow-labs/starter-kit, pull requests merged in 2023-02, with the labels that each got.

#169 Fix issue with shallow navigation
  components/Navbar/Navbar.tsx
  hooks/useOrderByQuery.ts
  hooks/usePaginateQuery.ts
  pages/collection/[chainId]/[id].tsx
  pages/explore/collections.tsx
  pages/explore/explore.tsx
  pages/explore/users.tsx
  pages/users/[id]/bids/placed.tsx
  pages/users/[id]/bids/received.tsx
  pages/users/[id]/created.tsx
  pages/users/[id]/offers/auction.tsx
  pages/users/[id]/offers/fixed.tsx
  pages/users/[id]/on-sale.tsx
  pages/users/[id]/owned.tsx
  pages/users/[id]/trades/purchased.tsx
  pages/users/[id]/trades/sold.tsx
Labels: priority:normal

#160 Implement token media size
  components/Token/Card.tsx
  components/Token/Header.tsx
  components/Token/Media.tsx
  pages/tokens/[id]/index.tsx
Labels: priority:normal

#166 Use proper img component
  components/Navbar/Navbar.tsx
  components/Sales/Auction/Inprogress/Inprogress.tsx
  components/Sales/Direct/Summary.tsx
  components/Sales/Open/Summary.tsx
  components/Wallet/Image.tsx
Labels: priority:normal

#173 Keep the image ratio in many components
  components/Collection/ListItem.tsx
  components/Filter/FilterAsset.tsx
  components/Offer/Form/Bid.tsx
  components/Sales/Auction/Form.tsx
  components/Sales/Auction/Inprogress/Inprogress.tsx
  components/Sales/Direct/Form.tsx
  components/Sales/Direct/Summary.tsx
  components/Sales/Open/Summary.tsx
  components/Select/Select.tsx
  components/Wallet/Account/WalletBalanceList.tsx
  components/Wallet/Image.tsx
  pages/checkout/[id].tsx
  pages/tokens/[id]/bid.tsx
Labels: bug

#167 Switch from Avatar to AccountImage in UserCard
  components/User/UserCard.tsx
Labels: priority:low

#172 invert order in sizes props
  components/Collection/CollectionCard.tsx
  components/Collection/CollectionHeader.tsx
  components/Token/Card.tsx
  components/Token/Header.tsx
  components/User/Profile/Banner.tsx
  components/User/UserCard.tsx
  pages/tokens/[id]/index.tsx
Labels: bug

#165 Refactor login system to prepare for wagmi
  components/Login/Form.tsx
  components/Modal/Login.tsx
  components/Navbar/Navbar.tsx
  components/Offer/Form/Bid.tsx
  components/Offer/Form/Checkout.tsx
  components/Referral/Form.tsx
  components/Token/Form/Create.tsx
  components/Wallet/Connectors/Coinbase.tsx
  components/Wallet/Connectors/Email.tsx
  components/Wallet/Connectors/Metamask.tsx
  components/Wallet/Connectors/WalletConnect.tsx
  pages/login.tsx
Labels: priority:low

#189 require `onActivate` and `onError` callbacks on wallet components
  components/Login/Form.tsx
  components/Wallet/Connectors/Coinbase.tsx
  components/Wallet/Connectors/Email.tsx
  components/Wallet/Connectors/Metamask.tsx
  components/Wallet/Connectors/WalletConnect.tsx
  components/Wallet/Connectors/_base.tsx
Labels: priority:low

#186 Normalize import of useAccount from Wagmi
  components/Wallet/Connectors/_base.tsx
  hooks/useEagerConnect.ts
Labels: priority:low

#188 run npm dedupe
  package-lock.json
Labels: priority:low

#190 Remove useExecuteOnAccountChange hook
  hooks/useExecuteOnAccountChange.ts
  pages/checkout/[id].tsx
  pages/collection/[chainId]/[id].tsx
  pages/explore/explore.tsx
  pages/tokens/[id]/bid.tsx
  pages/users/[id]/created.tsx
  pages/users/[id]/on-sale.tsx
  pages/users/[id]/owned.tsx
Labels: priority:low

#187 Fix the flickering in the navbar when logged in
  components/Navbar/Navbar.tsx
Labels: priority:normal
